export enum Type {
  RESTAURANT = 'RESTAURANT',
  PHARMACY = 'PHARMACY',
  MARKET = 'MARKET',
  BEER = 'BEER',
  PETS = 'PETS',
  SHOPPING = 'SHOPPING',
}

export enum SubType {
  MEET = 'MEET',
  SWEET = 'SWEET',
  SAVORY = 'SAVORY',
  ORIENTAL = 'ORIENTAL',
  HEALTHY = 'HEALTHY',
  SPORT = 'SPORT',
  BOOK = 'BOOK',
  GIFT = 'GIFT',
  ELECTRONICS = 'ELECTRONICS',
  COSMETIC = 'COSMETIC',
  FURNITURE = 'FURNITURE',
}
